### ISSUE TITLE
Learning: why do you use dispatchNow in controllers?

### ISSUE THREAD

**Issue by pr4xx** [laravelio/portal#244]
Hey, this is a question for learning rather then an issue.
In your controller classes, you always use `dispatchNow()` for doing the the real work like creating replies etc. I wonder why do you use this approach? What are the benefits instead of doing it directly in the controller?

Cheers

**Comment by driesvints** [comment]
Heya, sorry to keep you waiting. I wanted to take my time to properly explain this. So there are a couple of reasons why I take this approach.

First of all DRY: by moving all of the logic towards commands (in this case we're using "jobs" but it's the same principle) we can re-use the commands anywhere in the app. They're completely de-coupled from the presentation layer except for a few named constructors.

Second reason is that because we're using commands we get a complete list of everything our app can "do". If you visit the `app/jobs` directory you can see an entire list of actions the app can perform. This works also well into the mindset of DDD. Think of the commands there as Domain services. I'm planning on moving a bit more logic from the models to these commands so we can keep our models cleaner and slim but that for a future update.

Third reason is that I don't want my controllers to "do" anything. Controllers merely pass along data to the appropriate services and send responses back. They live in the presentation layer of your app and need to be unaware of anything too specific to your domain. By taking this approach our controllers become super slim and small and are easy to digest and read through.

There are more smaller benefits but these are the top ones. Hope this helps a bit. Feel free to ask more questions if you want! :)

**Comment by pr4xx** [comment]
Thank you very much for the explanation.
It makes sense to me now and I think I will try this in my next project. However, you still use the request validation feature. What if you dispatch a job somewhere else in the code. You would still have to validate it before you call the job right? Is this a good practise? What about error handling in the job if no validation has been done before?

**Comment by driesvints** [comment]
@pr4xx This is a really good remark. This approach indeed requires you to validate the data upfront. We could add some extra validation inside the constructor of the command. If we would be working with Doctrine I would do this inside the constructor of the entities. Of course you can't perform all the validation inside of the command, just a few basic things.

If you look at [the `RegisterUser` command](https://github.com/laravelio/portal/blob/master/app/Jobs/RegisterUser.php#L85) you can see that we're validating two things here. This works well and adds an extra layer of validation that makes sure the data is correct before we attempt to persist it. 

There's definitely no harm in adding more validation to your commands but you'll need to handle the exceptions properly when they're throw. Request validation up-front makes this easy. My suggestion for this particularly app would be to rely on request validation in the first place and do whatever you can in the command if it's really needed. At this point I'd leave the commands as is but I might add more validation in the future if I see the need.

**Comment by lukashl** [comment]
Why synchronously jobs instead events?

**Comment by driesvints** [comment]
> Why synchronously jobs instead events?

At the moment I'm dispatching commands from controllers. Events may be later added when I have need for them.

**Comment by BobbyBorisov** [comment]
@lukashl as far as i know events refer to things that already have happened(e.g. UserRegistered, UserConfirmed) and jobs are more like tasks that need to be done(e.g. CreateUser, BanUser).
